### ISSUE TITLE
Error Running Dapper (Copying Files)

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/tool-dapploy-nodejs#12]
Observed: Running Dapper fails with error
Expected: No Error

 $ Exporting Web3 module to ./build/js/scsc-web3.js
Copying /Users/arietrouw/GitHub/tool-dapploy-nodejs/src/web3template.js to /tmp/temp999
 $ Copying dapper interface from  /tmp/temp999 to /Users/arietrouw/GitHub/tool-dapploy-nodejs/src/../node_modules/tool-dapper-react/src/web3.js
 $ Moving /tmp/temp999 to ./build/js/scsc-web3.js
 $ Copying contracts locally to ./build/abi
 $ Copying dapper contracts locally to ./node_modules/tool-dapper-react/src/ABI/
CAUGHT ERR: { Error: Command failed: cp -R build/contracts/* ./node_modules/tool-dapper-react/src/ABI/
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
  killed: false,
  code: 64,
  signal: null,
  cmd:
   'cp -R build/contracts/* ./node_modules/tool-dapper-react/src/ABI/' }
Failed to compile.

In Browser: 

Failed to compile
./src/web3.js
Module not found: Can't resolve './../abi/StandardToken.json' in '/Users/arietrouw/GitHub/tool-dapploy-nodejs/node_modules/tool-dapper-react/src'
This error occurred during the build time and cannot be dismissed.

**Comment by klivin** [comment]
run dapper with no params now
