### ISSUE TITLE
dapploy init overwrites files

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/tool-dapploy-nodejs#27]
Observed: Running "dapploy init" in an existing folder blows away the package.json file (and possibly others)

Expected: Either warn the user of this or make updates to the files as needed instead of overwriting

**Comment by klivin** [comment]
Fixed.  I added error and don't allow continuing, as dapploy init should not be used on existing projects.  You can however use `dapploy init -g` to add a .dapploy config file
