### ISSUE TITLE
redesign Data Vault IPFS tokenizer

### ISSUE THREAD

**Issue by justinffortier** [XYOracleNetwork/tool-dapploy-nodejs#4]

**Comment by justinffortier** [comment]
➤ Paola Batiz commented:

@Kevin Weiler Wanted to touch base here and see when we should schedule some time?

**Comment by justinffortier** [comment]
➤ Kevin Weiler commented:

Hi @Paola Batiz , would love to catch up with you this afternoon some time maybe around 1 or 2PM? We can chat on slack or get on a call...I am thinking that the dapper project may be served with a higher priority of focus at the moment as I discovered IPFS is already working on a web ui for generic file storage kind of thing

**Comment by justinffortier** [comment]
➤ Paola Batiz commented:

hi @Kevin Weiler 2pm sounds good :) I'll send an invite

**Comment by klivin** [comment]
This is on the backburner as the re-design of the Dapper UI takes precedence

**Comment by justinffortier** [comment]
➤ Paola Batiz commented:

@Justin Fortier should we set a hard deadline for this one?

**Comment by justinffortier** [comment]
➤ Justin Fortier commented:

@Paola Batiz We should push this way out to be honest.

**Comment by justinffortier** [comment]
➤ Paola Batiz commented:

@Justin Fortier ok awesoem :)

**Comment by klivin** [comment]
removed samples as they are difficult to upkeep and add little
