### ISSUE TITLE
Path issue in dapploy init

### ISSUE THREAD

**Issue by SilverHammer** [XYOracleNetwork/tool-dapploy-nodejs#46]
Seems there is an error in copy command.
This:
cp -rp /usr/local/lib/node_modules/tool-dapploy-nodejs/src/../templates/template-solidity/ my-first-coin

should be:
cp -rp /usr/local/lib/node_modules/tool-dapploy-nodejs/src/../templates/template-solidity/* my-first-coin

otherwise it fails:

XXXXXXX@Archiver:~/XYO/dapploy/tool-dapploy-nodejs$ dapploy init my-first-coin -s ERC20
 $ Parsing config .dapploy
 $ Initializing project with ERC20 
 $ Creating truffle project in my-first-coin from /usr/local/lib/node_modules/tool-dapploy-nodejs/src/../templates/template-solidity/
 $ Copying /usr/local/lib/node_modules/tool-dapploy-nodejs/src/../templates/template-solidity/ to my-first-coin
{ Error: Command failed: mkdir -p my-first-coin &&   cp -rp /usr/local/lib/node_modules/tool-dapploy-nodejs/src/../templates/template-solidity/ my-first-coin &&   cp my-first-coin/adapters/ERC20Adapter.sol my-first-coin/contracts/
cp: cannot stat 'my-first-coin/adapters/ERC20Adapter.sol': No such file or directory

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'mkdir -p my-first-coin &&   cp -rp /usr/local/lib/node_modules/tool-dapploy-nodejs/src/../templates/template-solidity/ my-first-coin &&   cp my-first-coin/adapters/ERC20Adapter.sol my-first-coin/contracts/' }
XXXXXXX@Archiver:~/XYO/dapploy/tool-dapploy-nodejs$ 

The is no "adapters" directory or "contracts" directory created in the "my-first-coin" directory. However,they are in the "template-solidity" Directory

**Comment by klivin** [comment]
Fixed in #54
